### ISSUE TITLE
UI: use autoscale information for graphview and PNG image generation

### ISSUE THREAD

**Issue by till-f** [till-f/es-tdk#5]
* load in image generation when available (separate issue)

**Comment by till-f** [comment]
* an entry "GLOBAL", "autoscale", "true" is written into .db files, if autoscale should be performed after opening / before image generation
* can be tested using /fzi.mottem.examples.visualization/pts/ExampleTracing.pts (first plot is auto-scaled)

**Comment by KKatev** [comment]
Worked on the test case ExampleTracing.pts (ExampleTracing_0_Testgraph2.db) - The PNG is scaled correctly.
The autoscale only has a certain time frame in which it can be called correctly, so this may not work for larger data sets. Should be tested on real data.
